import type { NextPage } from 'next';
import Head from 'next/head';
import { useTranslation } from 'next-i18next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { LanguageSwitcher, Login } from '../components';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const [t] = useTranslation('common');

  // const onToggleLanguageClick = (newLocale: string) => {
  //   const { pathname, asPath, query } = router;
  //   router.push({ pathname, query }, asPath, { locale: newLocale });
  // };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <Trans i18nKey="blog.optimized.answer">
          Then you may have a look at{' '}
          <a href={t('blog.optimized.link')}>this blog post</a>.
        </Trans> */}
        <LanguageSwitcher
          locale={t('locale')}
          title={t('locale-modal-title')}
        />
        {t('greetings')}
        <Login
          identifierText={t('identifier-text')}
          passwordText={t('password-text')}
          loginText={t('controls.login')}
        />

        {/* alternative language change without using Link component
          <button onClick={() => onToggleLanguageClick(changeTo)}>
            {t('change-locale', { changeTo })}
          </button>
          */}
      </main>
    </div>
  );
};

export const getStaticProps = async ({ locale }: any) => ({
  props: {
    ...(await serverSideTranslations(locale, ['common'])),
  },
});

export default Home;
